import { FC } from "react"
import Head from "next/head"
import { Layout } from "antd"
import HeaderStyled from "./HeaderStyled"
import InfromationsEcommerce from "./InfromationsEcommerce"
import NavEcommerce from "./NavEcommerce"

const { Header } = Layout

const HeaderCmp: FC = () => {

  return (
    <HeaderStyled>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/panier.png" />
      </Head>
      <Header className="site__header__css">
        <InfromationsEcommerce />
      </Header>
      <NavEcommerce />
    </HeaderStyled>
  )
}

export default HeaderCmp